//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Capgemini.Infra.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CADASTRO
    {
        public int IdCadastro { get; set; }
        public string PrimeiroNome { get; set; }
        public string UltimoNome { get; set; }
        public string CPF { get; set; }
        public string Senha { get; set; }
        public string Sexo { get; set; }
        public string Endereco { get; set; }
        public string Rua { get; set; }
        public string Numero { get; set; }
        public string Complemento { get; set; }
        public string CEP { get; set; }
        public string Email { get; set; }
    }
}
